# Generated by Django 2.2.6 on 2019-11-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviber',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userviber',
            name='viber_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
